<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.data.umac.mo/service/aboutum/public_holidays/v1.0.0/all");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Authorization: Bearer d9dbbb9c-d06d-3066-8502-c8b6c4e766a6";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$get_data = json_decode($result, true);

// foreach($get_data['_embedded'] as $result_data) {
//     echo $result_data['date'],'<br>';

//     if($result_data['holiday'] == 'W'){
//         echo "Whole day is a holiday",'<br>';
//     }
//     if($result_data['holiday'] == '1'){
//         echo "Session 1, which stands for morning session is holiday",'<br>';
//     }
    
//     if($result_data['holiday'] == '2'){
//         echo "Session 2, which stands for afternoon session is holiday",'<br>';
//     }
// }


?>